sudo: required
services:
  - docker

before_install:
  - docker-compose build
install: npm install
 script:
  - docker-compose up
deploy:
  provider: "elasticbeanstalk"
  region: "us-east-2",
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-550229037490"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
